### ISSUE TITLE
When we click on the REVIEW in the header then the review text must have some space above it, it will be better.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Ankur-client#13]
**Actual result:**
When we click on the REVIEW in the header then the review text must have some space above it, it will be better.
https://desipehnava.com/pages/reviews
![image](https://user-images.githubusercontent.com/102131636/182120022-84947db1-1a4d-45fc-96aa-bbde1ba48dc0.png)
**Expected result:**
It must have some space above it, it will be much better.

**Comment by ui-kuldeep** [comment]
only home page design, not an other page

**Comment by sudhanshu0603** [comment]
ok
