### ISSUE TITLE
When we add any product to the cart then the count have to come in the header.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Ankur-client#24]
**Actual result:**
When we add any product to the cart then the count have to come in the header.
![image](https://user-images.githubusercontent.com/102131636/182132449-f0910d24-af2b-40e4-bca6-fb85108e59c9.png)
**Expected result:**
The count have to come on the cart icon on the header.

**Comment by devRitikTamrakar** [comment]
https://www.ilovecharacters.com/
you can check the same theme. this is by default functionality!
should I write custom code?

**Comment by sudhanshu0603** [comment]
ok
