### ISSUE TITLE
In product page, below the addtowishlist the text is coming very close to the button.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Ankur-client#28]
**Actual result:**
In product page, below the addtowishlist the text is coming very close to the button.
https://desipehnava.com/collections/top/products/blue-floral-top-for-women
![image](https://user-images.githubusercontent.com/102131636/182138114-592125a8-3b3e-4cf5-bf5b-04397fdae853.png)
**Expected result:**
The text below the addto wishlist button have some space it will be better.

**Comment by ui-kuldeep** [comment]
only home page design, not product page design

**Comment by sudhanshu0603** [comment]
ok, resolved
