### ISSUE TITLE
The extra spacing are coming on some of the pages of the footer.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Ankur-client#32]
**Actual result:**
The extra spacing are coming on some of the pages of the footer.
https://desipehnava.com/pages/aboutus
https://desipehnava.com/pages/aks-kids-dress-size-chart
![image](https://user-images.githubusercontent.com/102131636/182152815-ef880c4a-8833-453d-a5fb-421537f69f5e.png)
![image](https://user-images.githubusercontent.com/102131636/182152832-cd69aaee-690b-4799-b644-c96abd9e1159.png)

**Expected result:**
At the end of the text content, spacing should be equal in all the pages.

**Comment by ui-kuldeep** [comment]
only home page design, not other page

**Comment by sudhanshu0603** [comment]
ok, resolved
