### ISSUE TITLE
In contact us form, email is not clickable.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Ankur-client#45]
**Actual result:**
In contact us form, email is not clickable.
https://desipehnava.com/pages/contact-us
![image](https://user-images.githubusercontent.com/102131636/182769339-03ec9f8c-022e-4dea-a0cb-2bc95526e2ca.png)

**Expected result:**
The email have to be clickable.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
