### ISSUE TITLE
In contact us form, after filling and deleting input field the error message for blank input field is not coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Ankur-client#48]
**Actual result:**
In contact us form, after filling and deleting input field the error message for blank input field is not coming.
https://desipehnava.com/pages/contact-us
![image](https://user-images.githubusercontent.com/102131636/182770995-12be07cf-d858-43d5-abfd-2eee70be2c13.png)

**Expected result:**
The after filling and deleting data from input field, the error message have to come for empty input field.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  message will optional, no need to validate

**Comment by sudhanshu0603** [comment]
ok
