### ISSUE TITLE
In footer,  when we click on the chatbot then the text of the chatbot is overlapping.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Ankur-client#9]
**Actual result:**
In footer,  when we click on the chatbot then the text of the chatbot is overlapping.
![image](https://user-images.githubusercontent.com/102131636/182114323-748a78fb-47a9-414a-9856-bcbf9c8e1081.png)
**Expected result:**
The text should not overlapp when we click on the chatbot in footer.

**Comment by devRitikTamrakar** [comment]
https://e3w2v5lbfd2hv58g-26128868.shopifypreview.com/
in other projects you can see this problem, it means, it is coming from the app.

**Comment by sudhanshu0603** [comment]
,we do not have the access for now
